### ISSUE TITLE
Expose to_safe_layer_name on REST API.

### ISSUE THREAD

**Issue by raitisbe** [jirik/layman#153]
If we could call unidecode function on server instead of relying on client side unidecode npm library to do the transliteration before creating new layer, it would save us 400KB of bundle size.

**Comment by jirik** [comment]
Layman now offers option to layer's `name` on [POST Layers](https://github.com/jirik/layman/blob/master/doc/rest.md#post-layers). The name may include any unicode character. Layman cleans such layername to appropriate form, uses the clean name for the layer and returns the clean name in response.

**Example**

Request parameter
- name: `řčúpčřšlú.ú) šč)úřů)ščú šqč§w)§ túépi 4`

Response:
```
[
  {
    "name": "rcupcrslu_u_scuruscu_sqcsswss_tuepi_4",
    "url": "http://layman.lesprojekt.cz/rest/jiri_kozel_cz/layers/rcupcrslu_u_scuruscu_sqcsswss_tuepi_4",
    "uuid": "885fd787-4d19-4c1c-b196-77f307cdd817"
  }
]
```

The same works for maps.

Is this suitable for your use case?

**Comment by jirik** [comment]
Closing as we have no response from @raitisbe
