### ISSUE TITLE
WMS support of other spatial reference systems (SRS)

### ISSUE THREAD

**Issue by jirik** [jirik/layman#168]

**Comment by jirik** [comment]
Related to #64

**Comment by fzadrazil** [comment]
Following SRS should be supported for a start, EPSG codes: 4326, 3857, 5514, 102067, 32634, 3059.
However, it would be probably desirable to support all the systems used by [https://geoportal.cuzk.cz/(S(pkshjm4j4aecfvlj5d2u4qsh))/Default.aspx?mode=TextMeta&side=sit.trans&text=souradsystemy](url)

**Comment by jirik** [comment]
Probably also 32633
