### ISSUE TITLE
Creating new layer from Shapefile causes Layman to crash

### ISSUE THREAD

**Issue by fzadrazil** [jirik/layman#175]
![image](https://user-images.githubusercontent.com/48727502/100895631-13781700-34be-11eb-9b4e-a6e7f34fed9a.png)
After inserting new layer from Shp (epsg:4326), all the subsequent requests for this layer ends with proxy error. Tried on three different servers with the same result, using Layman 1.7.3.

**Comment by bvj** [comment]
not only subsequent requests for this layer, but all requests for any layer

**Comment by jirik** [comment]
After some investigation it seems that Layman freezes on posting new feature type to GeoServer:
https://github.com/jirik/layman/blob/66cc4ee5d083fab0bf47c69a0cfc6e0dd11acaff/src/layman/layer/geoserver/__init__.py#L94

The reason of this freezing is still unknown. It freezes on 1.7.3, but it's not happening after downgrade to 1.7.2.
