### ISSUE TITLE
Not recognized Micka version

### ISSUE THREAD

**Issue by bvj** [jirik/layman#187]
Micka is 6.045 (rev. 2020-11-20.01), in .env settings file: MICKA_ACCEPTED_VERSION=6.045:2020-11-20.01

layman log:
Waiting for Micka, url=https://hub.plan4all.eu/cat/about
Traceback (most recent call last):
  File "src/wait_for_deps.py", line 140, in <module>
    main()
  File "src/wait_for_deps.py", line 110, in main
    assert (version_match and len(version_match.groups()) == 2), 'Unknown version of Micka!'
AssertionError: Unknown version of Micka!

Layman v1.7.2

**Comment by jirik** [comment]
@bvj Thanks for reporting. Layman uses some regexp to parse Micka's version from /about page. It seems that version 6.045 has new formatting of that page, so we need to change our regexp.

Example:
- https://www.agrihub.cz/micka/about (previous versions)
- https://hub.plan4all.eu/cat/about (new version)
