### ISSUE TITLE
Creating layer with categorized SLD causes rendering exception

### ISSUE THREAD

**Issue by fzadrazil** [jirik/layman#205]
WMS GetMap operation throws 

`<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://hub.lesprojekt.cz/client/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="internalError"> Rendering process failed java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: invalid input syntax for type double precision: "" Position: 610 ERROR: invalid input syntax for type double precision: "" Position: 610 </ServiceException>
</ServiceExceptionReport>`

The issue can be investigated on Layman layer https://hub.lesprojekt.cz/rest/fzadrazil/layers/kategorie
[data.zip](https://github.com/jirik/layman/files/5769285/data.zip)

**Comment by jirik** [comment]
In SLD, there is filter
```
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:Or>
              <ogc:PropertyIsEqualTo>
                <ogc:PropertyName>n</ogc:PropertyName>
                <ogc:Literal></ogc:Literal>
              </ogc:PropertyIsEqualTo>
              <ogc:PropertyIsNull>
                <ogc:PropertyName>n</ogc:PropertyName>
              </ogc:PropertyIsNull>
            </ogc:Or>
          </ogc:Filter>
```
that does not correspond with data type of `n` attribute, more specifically part `<ogc:Literal></ogc:Literal>`. Data type of `n` attribute is number, however this literal is empty string.

You can fix it for example by adding some number, e.g. `<ogc:Literal>50</ogc:Literal>`.
