### ISSUE TITLE
Unify body of post/patch_layer/map in util

### ISSUE THREAD

**Issue by jirik** [jirik/layman#31]
Body will be structured to three parts:
- call sync post/patch_layer/map on subset of internal sources `[:start_at]`
  - In case of map, those methods already exists, in case of layer, these methods should be created from current update_info.
  - Pass parameters as it's already implemented in map util
- call delete_layer/map on subset of internal sources `[start_at:]`
- call async tasks on subset of internal sources `[start_at:]`
  - already described in #13 and implemented 

Note: there must be no sync task to be called after the first async task.

**Comment by index-git** [comment]
Stale/not actual.
