### ISSUE TITLE
Dynamic proxy base URL (requires geoserver 2.16)

### ISSUE THREAD

**Issue by raitisbe** [jirik/layman#41]
Could we upgrade geoserver to 2.16?

It has this " Use headers for Proxy URL" checkbox, which is needed if we want to run the same layman on different domains: https://groundwater.smartagro.lv and http://groundwater.bosc.lv in our case)

https://docs.geoserver.org/stable/en/user/configuration/globalsettings.html:
> For instance, to allow different protocols (http and https) and different hostnames, the proxy base URL field may be changed to: ${X-Forwarded-Proto}://${X-Forwarded-Host}/geoserver

**Comment by jirik** [comment]
We can, but it's not in priority list now. BTW upgrading GeoServer is probably not enough. Layman's REST API is bound to single URL and not aware of X-Forwarded* headers. Micka is probably similar case.

Why do you need to run single Layman on different domains? Why not to have single instance of Layman on single domain and use it from any domains you need?

**Comment by raitisbe** [comment]
Because I get these errors then:
![image](https://user-images.githubusercontent.com/395514/73745758-6aa54200-475c-11ea-978e-3334197fc9ec.png)

**Comment by raitisbe** [comment]
And I cant run layman on https because of #42 .

**Comment by jirik** [comment]
Please look at https://github.com/jirik/layman/issues/42#issuecomment-584647999 It shows how to run layman with https.
If it works, we can close both tickets.

**Comment by jirik** [comment]
Closing as #42 was resolved.
