### ISSUE TITLE
Layer stuck on pending forever

### ISSUE THREAD

**Issue by raitisbe** [jirik/layman#44]
![image](https://user-images.githubusercontent.com/395514/74823100-db2c9100-530e-11ea-9a73-db930f100ea1.png)

**Comment by jirik** [comment]
Please post
- exact version of Micka (git commit or tag)
- logs from `layman*` containers
- name and traceback of failed tasks from flower

**Comment by raitisbe** [comment]
I dont think its Micka related. Could be because of updating layer in quick succession, when moving points of polygon for example. Will try to replicate on a clean db.

**Comment by raitisbe** [comment]
After stoping and starting the docker containers I dont see PENDING state anymore, even after modifying layer quickly. Would like to leave the issue open for a while in case somebody else manages to crash the layer again. Which containers logs would be useful?

**Comment by jirik** [comment]
`layman` and `layman_celery_worker*` containers are usually the most helpful.

BTW PATCH Layer is really not meant for updating layer in quick succession. I recommend to use WFS in this case.

**Comment by raitisbe** [comment]
Thanks about WFS. Should have synced using that from the start.

**Comment by jirik** [comment]
Closing, as there if no further information about this issue and not reported in last 6 months.
