### ISSUE TITLE
Configurable nginx ports through .env file

### ISSUE THREAD

**Issue by raitisbe** [jirik/layman#61]
nginx:
...
      ports:
         - ${LAYMAN_PUBLIC_PORT}:80
would be nice

**Comment by jirik** [comment]
We can name it LAYMAN_LOCALHOST_PORT, as it's not necessarily port for outside world.

**Comment by raitisbe** [comment]
sure

**Comment by jirik** [comment]
Requires Micka to support http://localhost:1234/micka configuration. Currently either custom port or custom path is supported, but not both,

**Comment by jirik** [comment]
Stale
