### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jirik** [jirik/layman#71]
- [E402: import not at top of file with sys.path](https://pep8.org/#imports)
   - to be discussed
- [E501: line too long](https://pep8.org/#maximum-line-length)
   - to be discussed
- [W503: Line break occurred before a binary operator](https://pep8.org/#break-before-or-after-binary-operator)
   - to be discussed

**Comment by jirik** [comment]
Questions
- Do we need all flake8, pycodestyle, and pylint?
- Is pylint-exit used?

**Comment by index-git** [comment]
We leave the last three in the code as we do not see it worth it to solve it now.
