### ISSUE TITLE
Categorization of tests

### ISSUE THREAD

**Issue by jirik** [jirik/layman#91]
integration tests. vs unit tests, maybe other categories
order of tests
dependencies between tests

**Comment by jirik** [comment]
Consider using https://www.tutorialspoint.com/pytest/pytest_grouping_the_tests.htm

**Comment by index-git** [comment]
More info for markers in Pytest: https://docs.pytest.org/en/2.9.2/example/markers.html

**Comment by jirik** [comment]
Stale
