### ISSUE TITLE
Display installed version of Layman

### ISSUE THREAD

**Issue by fzadrazil** [jirik/layman#99]
Displaying installed version of Layman somewhere in the GUI of the client would be useful when administering the system.

**Comment by jirik** [comment]
Just internal notes:
- what info we need:
  - **version**, e.g. `1.1.3-dev` or `1.1.3`
  - **commit**, e.g. `2567b40` or `1d4df98`
- would be nice:
  - *branch*, e.g. `master` or `issue-123`

The **version** should be stored in git repo, e.g. in [_version.py](https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package). Most of the time, the value will be `<next-version>-dev`. During release, two commits are automatically produced:
  - First commit changes `<next-version>-dev` to `<next-version>`. This commit is tagged as `v<next-version>` and released, so "next-version" becomes "current-version".
  - Second commit changes `<current-version>` to `<new-next-version>-dev`

This **version** management is used in https://github.com/openlayers/openlayers

The **commit** (and *branch*) should not be stored in git repo. We can try to produce the file on every startup (`make ...`) using some `git ... > git-commit.txt` command. If git is not installed, or the command failed for some reason, `git-commit.txt` is at least deleted.

Then Layman can read both **version** and **commit** from above mentioned places. It should handle situation when **commit** is not known (`git-commit.txt` does not exist).

**Comment by index-git** [comment]
I see three options for _version.py file:
1) GitHub action
- run after push, not each commit
- you can change last commit, but it's little bit strange in git history
- add new change to commit
2) Client side hook
- add new change to commit
- need to distribute it in each git client (every contributor, every workstation)
3) Make action for release
- stored in git
- the is a way to bypass it

**Comment by jirik** [comment]
+1 for option 3 (`make` action). We will probably need to distinguish following actions:
- release new minor version (without `-dev` suffix), start next minor version (with `-dev` suffix)
- start new patch version (with `-dev` suffix) for hotfixes
- release new patch version (without `-dev` suffix)

**Comment by index-git** [comment]
Actions for Makefile:

```.PHONY: test

version_tuple := $(subst ., ,$(version:%=%))
version_major := $(word 1,$(version_tuple))
version_minor := $(word 2,$(version_tuple))
version_patch := $(word 3,$(version_tuple))
$(eval version_minor_next=$(shell echo $$(($(version_minor)+1))))
$(eval version_patch_next=$(shell echo $$(($(version_patch)+1))))

tag:
	echo "Version=$(version)" > _version.py
	git add _version.py
	git commit -m "Release $(version)"
	git tag -a "v$(version)" -m "v$(version)"
	git push origin "v$(version)"
	echo "Version=$(version_major).$(version_minor_next).$(version_patch)-dev" > _version.py
	git add _version.py
	git commit -m "Start development of $(version_major).$(version_minor_next).$(version_patch)-dev"
	git push

tag-patch:
	echo "Version=$(version)" > _version.py
	git add _version.py
	git commit -m "Release $(version)"
	git tag -a "v$(version)" -m "v$(version)"
	git push origin "v$(version)"
	echo "Version=$(version_major).$(version_minor).$(version_patch_next)-dev" > _version.py
	git add _version.py
	git commit -m "Start development of $(version_major).$(version_minor).$(version_patch_next)-dev"
	git push
```

**Comment by jirik** [comment]
- We will keep branches MAJOR.MINOR.x till there is a chance of patch release
- Single action in Makefile: release
    - no parameters, it requires correct branch
    - gets version from version.txt
    - checks combination of branch name and version value
       - master + MAJOR.MINOR.0-dev
       - MAJOR.MINOR.x + MAJOR.MINOR.[1-9][0-9]*-dev
    - makes summary, asks for permisson
    - creates release commit, tag it, push
    - in case of minor release, create also its branch X.Y.x
    - commit with next major or patch version, push
- Use bash

**Comment by jirik** [comment]
Basic version implemented. For advance functionality, #264 and #265 are created.
